var productJSON = {
  taxes: [],
  exceptions: [],
  _product_wholesale: [],
  parentId: 0,
  c_options: {
    product_image: null,
    product_image_src:
      'https:\/\/cdn.mmsports.se\/images\/P\/bsc-whey100-403g-belgianchocolate-medium-1pack.jpg',
    pconf_price: 0,
    default_price: 129,
    alter_currency_rate: 1,
    ruby_rates_active: true,
    ruby_rates_display_only_alt: 'N',
    alter_currency_symbol: '',
    list_price: 0,
    price: 129,
    orig_price: 121.69811320754717,
    original_price: 179,
    max_quantity: 99,
    min_quantity: 1,
    avail: 1594,
    forsale: 'Y',
    dynamic_save_money_enabled: true,
    quantity_input_box_enabled: false,
    max_image_width: 0,
    max_image_height: 0,
    price_history: 0,
  },
  variants: {
    54723: [
      [
        129,
        1594,
        { src: '', width: 0, height: 0, _x: 0, _y: 0 },
        1,
        129,
        '2350970010-2000',
        0,
        0,
        179,
        1,
        {
          variant_thumbnail_path:
            'https:\/\/cdn.mmsports.se\/resized\/category\/D\/Whey100-403g-Vanilla_250320.jpg',
        },
        7340224402277,
        'Storlek: 400 g Smak: Vanilla',
        0,
        null,
        false,
        '<h2>Body Science Whey 100% Vanilla<\/h2>\r\n<p><strong>Proteinpulver med smak av vanilj. Inneh&aring;ller s&ouml;tningsmedel. Inneh&aring;ller laktasenzym.<br \/>Nettovikt:<\/strong>&nbsp;403 g (13 portioner).<br \/><strong>Portionsstorlek:<\/strong>&nbsp;31 g (~1 dl).&nbsp;Skopa ing&aring;r ej.<\/p>\r\n<p><strong>Anv&auml;ndning:<\/strong>&nbsp;<span class="TextRun SCXW32296401 BCX8" lang="SV-SE" xml:lang="SV-SE"><span class="NormalTextRun SCXW32296401 BCX8">Blanda 3<\/span><span class="NormalTextRun SCXW32296401 BCX8">1<\/span><span class="NormalTextRun SCXW32296401 BCX8">&nbsp;<\/span><span class="NormalTextRun SCXW32296401 BCX8">g<\/span><span class="NormalTextRun SCXW32296401 BCX8">&nbsp;<\/span><span class="NormalTextRun SCXW32296401 BCX8">med 2 dl vatten eller laktosfri mj&ouml;lk. M&auml;ngden v&auml;tska kan &ouml;kas eller minskas efter behov. Rekommenderat intag:&nbsp;<\/span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW32296401 BCX8">2<\/span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW32296401 BCX8">-<\/span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW32296401 BCX8">3<\/span><span class="NormalTextRun SCXW32296401 BCX8">&nbsp;portioner per dag.<\/span><\/span><span class="EOP SCXW32296401 BCX8">&nbsp;<\/span><\/p>\r\n<p><strong>Ingredienser:<\/strong>&nbsp;<span class="TextRun SCXW243586436 BCX8" lang="SV-SE" xml:lang="SV-SE">Vassleproteinkoncentrat fr&aring;n&nbsp;<\/span><strong><span class="TextRun SCXW243586436 BCX8" lang="SV-SE" xml:lang="SV-SE">mj&ouml;lk<\/span><\/strong><span class="TextRun SCXW243586436 BCX8" lang="SV-SE" xml:lang="SV-SE">&nbsp;(inneh&aring;ller emulgeringsmedel solroslecitin,&nbsp;<\/span><strong><span class="TextRun SCXW243586436 BCX8" lang="SV-SE" xml:lang="SV-SE">soja<\/span><\/strong><span class="TextRun SCXW243586436 BCX8" lang="SV-SE" xml:lang="SV-SE"><span class="NormalTextRun SCXW243586436 BCX8">lecitin), stabiliseringsmedel (<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW243586436 BCX8">celllulosagummi<\/span><span class="NormalTextRun SCXW243586436 BCX8">), salt, s&ouml;tningsmedel (<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW243586436 BCX8">aspartam<\/span><span class="NormalTextRun SCXW243586436 BCX8">,&nbsp;<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW243586436 BCX8">acesulfam<\/span><span class="NormalTextRun SCXW243586436 BCX8">-K), arom, laktasenzym. Inneh&aring;ller en&nbsp;<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW243586436 BCX8">fenylalanink&auml;lla<\/span><span class="NormalTextRun SCXW243586436 BCX8">.<\/span><\/span><span class="EOP SCXW243586436 BCX8">&nbsp;<\/span><\/p>\r\n<p><strong>B&auml;st f&ouml;re utg&aring;ngen av:<\/strong>&nbsp;Se st&auml;mpel.<\/p>\r\n<p><strong>F&ouml;rvaringsanvisning:&nbsp;<\/strong><span class="NormalTextRun SCXW156182286 BCX8">I<\/span><span class="NormalTextRun SCXW156182286 BCX8">&nbsp;originalf&ouml;rpackning i rumstemperatur.<\/span><\/p>\r\n<table style="width: 100%; border: 1px solid #000000;" border="1" cellspacing="0" cellpadding="3">\r\n<tbody>\r\n<tr>\r\n<td colspan="3"><strong>N&auml;ringsinneh&aring;ll per 100 g och per portion 31 g.<\/strong><\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Energi<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1588 kJ\/378 kcal<\/td>\r\n<td style="text-align: right;" align="center" valign="top"><span class="NormalTextRun SCXW16501336 BCX8">4<\/span><span class="NormalTextRun SCXW16501336 BCX8">91<\/span><span class="NormalTextRun SCXW16501336 BCX8">&nbsp;<\/span>kJ\/117 kcal<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Fett<br \/>-varav m&auml;ttat fett<\/td>\r\n<td style="text-align: right;" align="center" valign="top">5,9 g<br \/>5,9 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1,8 g<br \/>1,8 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Kolhydrater<br \/>-varav sockerarter<sup>1<\/sup><\/td>\r\n<td style="text-align: right;" align="center" valign="top">3,9 g<br \/>3,9 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1,2 g<br \/>1,2 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Protein<\/td>\r\n<td style="text-align: right;" align="center" valign="top">77 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">24 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Salt<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1,32 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">0,41 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td colspan="3">&nbsp;<\/td>\r\n<\/tr>\r\n<tr>\r\n<td colspan="3"><sup>1&nbsp;<\/sup>Inneh&aring;ller naturligt f&ouml;rekommande socker.<br \/><\/td>\r\n<\/tr>\r\n<\/tbody>\r\n<\/table>\r\n<p>&nbsp;<\/p>\r\n<p><strong>&Ouml;vrig information:&nbsp;<\/strong>MM Sports str&auml;var efter att alltid ge dig korrekt information. Eftersom mindre f&ouml;r&auml;ndringar i produktinneh&aring;llet kan ske &ouml;ver tid, uppmanar vi dig att kontrollera informationen p&aring; produktens f&ouml;rpackning innan anv&auml;ndning.<\/p>',
      ],
      { 13157: 52793, 13158: 52794 },
      { 2: 7.299999999999997, 7: 0 },
      [],
    ],
    54724: [
      [
        129,
        813,
        { src: '', width: 0, height: 0, _x: 0, _y: 0 },
        1,
        129,
        '2350970010-2003',
        0,
        0,
        179,
        1,
        {
          variant_thumbnail_path:
            'https:\/\/cdn.mmsports.se\/resized\/category\/D\/Whey100-403g-ChocolateCake_250320.jpg',
        },
        7340224402307,
        'Storlek: 400 g Smak: Chocolate Cake',
        0,
        null,
        false,
        '<h2>Body Science Whey 100% Chocolate Cake<\/h2>\r\n<p><strong>Proteinpulver med smak av kladdkaka. Inneh&aring;ller s&ouml;tningsmedel.&nbsp;<strong>Inneh&aring;ller laktasenzym.<\/strong><br \/>Nettovikt:<\/strong>&nbsp;403 g (13 portioner).&nbsp;<br \/><strong>Portionsstorlek:<\/strong>&nbsp;31 g (~1 dl). Skopa ing&aring;r ej.<\/p>\r\n<p><strong>Anv&auml;ndning:<\/strong>&nbsp;<span class="TextRun SCXW166564963 BCX8" lang="SV-SE" xml:lang="SV-SE"><span class="NormalTextRun SCXW166564963 BCX8">Blanda 3<\/span><span class="NormalTextRun SCXW166564963 BCX8">1<\/span><span class="NormalTextRun SCXW166564963 BCX8">&nbsp;<\/span><span class="NormalTextRun SCXW166564963 BCX8">g<\/span><span class="NormalTextRun SCXW166564963 BCX8">&nbsp;med 2 dl vatten eller laktosfri mj&ouml;lk. M&auml;ngden v&auml;tska kan &ouml;kas eller minskas efter behov. Rekommenderat intag:&nbsp;<\/span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW166564963 BCX8">2<\/span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW166564963 BCX8">-<\/span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW166564963 BCX8">3<\/span><span class="NormalTextRun SCXW166564963 BCX8">&nbsp;portioner per dag.<\/span><\/span><span class="EOP SCXW166564963 BCX8">&nbsp;<\/span><\/p>\r\n<p><strong>Ingredienser:&nbsp;<\/strong><span class="TextRun SCXW47066648 BCX8" lang="SV-SE" xml:lang="SV-SE"><span class="NormalTextRun SCXW47066648 BCX8">V<\/span><span class="NormalTextRun SCXW47066648 BCX8">assleproteinkoncentrat fr&aring;n&nbsp;<\/span><\/span><strong><span class="TextRun SCXW47066648 BCX8" lang="SV-SE" xml:lang="SV-SE">mj&ouml;lk<\/span><\/strong><span class="TextRun SCXW47066648 BCX8" lang="SV-SE" xml:lang="SV-SE"><span class="NormalTextRun SCXW47066648 BCX8">&nbsp;(inneh&aring;ller emulgeringsmedel&nbsp;<\/span><span class="NormalTextRun SCXW47066648 BCX8">solros<\/span><span class="NormalTextRun SCXW47066648 BCX8">lecitin<\/span><span class="NormalTextRun SCXW47066648 BCX8">,&nbsp;<\/span><\/span><strong><span class="TextRun SCXW47066648 BCX8" lang="SV-SE" xml:lang="SV-SE">soja<\/span><\/strong><span class="TextRun SCXW47066648 BCX8" lang="SV-SE" xml:lang="SV-SE"><span class="NormalTextRun SCXW47066648 BCX8">lecitin<\/span><span class="NormalTextRun SCXW47066648 BCX8">),&nbsp;<\/span><span class="NormalTextRun SCXW47066648 BCX8">kakao, salt, arom, stabiliseringsmedel (cellulosagummi), s&ouml;tningsmedel (<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW47066648 BCX8">aspartam<\/span><span class="NormalTextRun SCXW47066648 BCX8">,&nbsp;<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW47066648 BCX8">acesulfam<\/span><span class="NormalTextRun SCXW47066648 BCX8">-K), laktasenzym. Inneh&aring;ller en&nbsp;<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW47066648 BCX8">fenylalanink&auml;lla<\/span><span class="NormalTextRun SCXW47066648 BCX8">.<\/span><\/span><strong>&nbsp;<\/strong><\/p>\r\n<p><strong>B&auml;st f&ouml;re utg&aring;ngen av:<\/strong>&nbsp;Se st&auml;mpel.<\/p>\r\n<p><strong>F&ouml;rvaringsanvisning:&nbsp;<\/strong><span class="NormalTextRun SCXW46572905 BCX8">I<\/span><span class="NormalTextRun SCXW46572905 BCX8">&nbsp;originalf&ouml;rpackning i rumstemperatur.<\/span><\/p>\r\n<table style="width: 100%; border: 1px solid #000000;" border="1" cellspacing="0" cellpadding="3">\r\n<tbody>\r\n<tr>\r\n<td colspan="3"><strong>N&auml;ringsinneh&aring;ll per 100 g och per portion 31 g:<\/strong><\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Energi<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1541 kJ\/367 kcal<\/td>\r\n<td style="text-align: right;" align="center" valign="top"><span class="NormalTextRun SCXW188397607 BCX8">4<\/span><span class="NormalTextRun SCXW188397607 BCX8">83<\/span><span class="NormalTextRun SCXW188397607 BCX8">&nbsp;<\/span>kJ\/<span class="NormalTextRun SCXW188397607 BCX8">11<\/span><span class="NormalTextRun SCXW188397607 BCX8">5<\/span><span class="NormalTextRun SCXW188397607 BCX8">&nbsp;<\/span>kcal<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Fett<br \/>-varav m&auml;ttat fett<\/td>\r\n<td style="text-align: right;" align="center" valign="top">6,4 g<br \/>5,8 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">2,0 g<br \/>1,8 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Kolhydrater<br \/>-varav sockerarter<sup>1<\/sup><\/td>\r\n<td style="text-align: right;" align="center" valign="top">4,8 g<br \/>3,4 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1,5 g<br \/>1,1 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Protein<\/td>\r\n<td style="text-align: right;" align="center" valign="top">70 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">22 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Salt<\/td>\r\n<td style="text-align: right;" align="center" valign="top">2,22 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">0,69 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td colspan="3">&nbsp;<\/td>\r\n<\/tr>\r\n<tr>\r\n<td colspan="3"><sup>1&nbsp;<\/sup>Inneh&aring;ller naturligt f&ouml;rekommande socker.<br \/><\/td>\r\n<\/tr>\r\n<\/tbody>\r\n<\/table>\r\n<p>&nbsp;<\/p>\r\n<p><strong>&Ouml;vrig information:&nbsp;<\/strong>MM Sports str&auml;var efter att alltid ge dig korrekt information. Eftersom mindre f&ouml;r&auml;ndringar i produktinneh&aring;llet kan ske &ouml;ver tid, uppmanar vi dig att kontrollera informationen p&aring; produktens f&ouml;rpackning innan anv&auml;ndning.<\/p>',
      ],
      { 13157: 52793, 13158: 52795 },
      { 2: 7.299999999999997, 7: 0 },
      [],
    ],
    54725: [
      [
        129,
        2452,
        { src: '', width: 0, height: 0, _x: 0, _y: 0 },
        1,
        129,
        '2350970010-2004',
        0,
        0,
        179,
        1,
        {
          variant_thumbnail_path:
            'https:\/\/cdn.mmsports.se\/resized\/category\/D\/Whey100-403g-Strawberry_250320.jpg',
        },
        7340224406954,
        'Storlek: 400 g Smak: Strawberry',
        0,
        null,
        false,
        '<h2>Body Science Whey 100% Strawberry<\/h2>\r\n<p><strong>Proteinpulver med smak av jordgubb. Inneh&aring;ller s&ouml;tningsmedel.&nbsp;<strong>Inneh&aring;ller laktasenzym.<\/strong><br \/>Nettovikt:<\/strong>&nbsp;403 g (13 portioner).&nbsp;<br \/><strong>Portionsstorlek:<\/strong>&nbsp;31 gram (~1 dl).&nbsp;Skopa ing&aring;r ej.<\/p>\r\n<p><strong>Anv&auml;ndning:<\/strong>&nbsp;Blanda 31 g med 2 dl vatten eller laktosfri mj&ouml;lk. M&auml;ngden v&auml;tska kan &ouml;kas eller minskas efter behov. Rekommenderat intag: 2-3 portioner per dag.<\/p>\r\n<p><strong>Ingredienser:<\/strong>&nbsp;<span class="TextRun SCXW34486065 BCX8" lang="SV-SE" xml:lang="SV-SE"><span class="NormalTextRun SCXW34486065 BCX8">V<\/span><span class="NormalTextRun SCXW34486065 BCX8">assleproteinkoncentrat fr&aring;n&nbsp;<\/span><\/span><strong><span class="TextRun SCXW34486065 BCX8" lang="SV-SE" xml:lang="SV-SE">mj&ouml;lk<\/span><\/strong><span class="TextRun SCXW34486065 BCX8" lang="SV-SE" xml:lang="SV-SE"><span class="NormalTextRun SCXW34486065 BCX8">&nbsp;(inneh&aring;ller emulgeringsmedel&nbsp;<\/span><span class="NormalTextRun SCXW34486065 BCX8">so<\/span><span class="NormalTextRun SCXW34486065 BCX8">lros<\/span><span class="NormalTextRun SCXW34486065 BCX8">lecitin<\/span><span class="NormalTextRun SCXW34486065 BCX8">,&nbsp;<\/span><\/span><strong><span class="TextRun SCXW34486065 BCX8" lang="SV-SE" xml:lang="SV-SE">soja<\/span><\/strong><span class="TextRun SCXW34486065 BCX8" lang="SV-SE" xml:lang="SV-SE"><span class="NormalTextRun SCXW34486065 BCX8">lecitin<\/span><span class="NormalTextRun SCXW34486065 BCX8">),&nbsp;<\/span><span class="NormalTextRun SCXW34486065 BCX8">arom,<\/span><span class="NormalTextRun SCXW34486065 BCX8">&nbsp;<\/span><span class="NormalTextRun SCXW34486065 BCX8">f&auml;rg&auml;mne (r&ouml;dbetsr&ouml;tt),&nbsp;<\/span><span class="NormalTextRun SCXW34486065 BCX8">stabil<\/span><span class="NormalTextRun SCXW34486065 BCX8">iseringsmedel (cellulosagummi)<\/span><span class="NormalTextRun SCXW34486065 BCX8">,<\/span><span class="NormalTextRun SCXW34486065 BCX8">&nbsp;<\/span><span class="NormalTextRun SCXW34486065 BCX8">salt,&nbsp;<\/span><span class="NormalTextRun SCXW34486065 BCX8">surhetsreglerande medel&nbsp;<\/span><span class="NormalTextRun SCXW34486065 BCX8">(<\/span><span class="NormalTextRun SCXW34486065 BCX8">&auml;ppelsyra<\/span><span class="NormalTextRun SCXW34486065 BCX8">)<\/span><span class="NormalTextRun SCXW34486065 BCX8">,&nbsp;<\/span><span class="NormalTextRun SCXW34486065 BCX8">s&ouml;tningsmed<\/span><span class="NormalTextRun SCXW34486065 BCX8">el (<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW34486065 BCX8">aspartam<\/span><span class="NormalTextRun SCXW34486065 BCX8">,&nbsp;<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW34486065 BCX8">acesulfam<\/span><span class="NormalTextRun SCXW34486065 BCX8">-K)<\/span><span class="NormalTextRun SCXW34486065 BCX8">,<\/span><span class="NormalTextRun SCXW34486065 BCX8">&nbsp;<\/span><span class="NormalTextRun SCXW34486065 BCX8">laktasenzym<\/span><span class="NormalTextRun SCXW34486065 BCX8">.&nbsp;<\/span><span class="NormalTextRun SCXW34486065 BCX8">Inneh&aring;ller en&nbsp;<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW34486065 BCX8">fenylalanink&auml;lla<\/span><span class="NormalTextRun SCXW34486065 BCX8">.<\/span><\/span><span class="EOP SCXW34486065 BCX8">&nbsp;<\/span><\/p>\r\n<p><strong>OBS:<\/strong>&nbsp;Viktigt med en m&aring;ngsidig och balanserad kost och h&auml;lsosam livsstil.<\/p>\r\n<p><strong>B&auml;st f&ouml;re utg&aring;ngen av:<\/strong>&nbsp;Se st&auml;mpel.<\/p>\r\n<p><strong>F&ouml;rvaringsanvisning:&nbsp;<\/strong>I originalf&ouml;rpackning i rumstemperatur.<\/p>\r\n<table style="width: 100%; border: 1px solid #000000;" border="1" cellspacing="0" cellpadding="3">\r\n<tbody>\r\n<tr>\r\n<td colspan="3"><strong>N&auml;ringsinneh&aring;ll per 100 g och per portion 31 g.<\/strong><\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Energi<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1541 kJ\/369 kcal<\/td>\r\n<td style="text-align: right;" align="center" valign="top">479 kJ\/114 kcal<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Fett<br \/>-varav m&auml;ttat fett<\/td>\r\n<td style="text-align: right;" align="center" valign="top">5,7 g<br \/>5,7 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1,8 g<br \/>1,8 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Kolhydrater<br \/>-varav sockerarter<sup>1<\/sup><\/td>\r\n<td style="text-align: right;" align="center" valign="top">4,6 g<br \/>4,1 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1,4 g<br \/>1,3 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Protein<\/td>\r\n<td style="text-align: right;" align="center" valign="top">74 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">23 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Salt<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1,29 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">0,40 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td colspan="3">&nbsp;<\/td>\r\n<\/tr>\r\n<tr>\r\n<td colspan="3"><sup>1&nbsp;<\/sup>Inneh&aring;ller naturligt f&ouml;rekommande socker.<br \/><\/td>\r\n<\/tr>\r\n<\/tbody>\r\n<\/table>\r\n<p>&nbsp;<\/p>\r\n<p><strong>&Ouml;vrig information:&nbsp;<\/strong>MM Sports str&auml;var efter att alltid ge dig korrekt information. Eftersom mindre f&ouml;r&auml;ndringar i produktinneh&aring;llet kan ske &ouml;ver tid, uppmanar vi dig att kontrollera informationen p&aring; produktens f&ouml;rpackning innan anv&auml;ndning.<\/p>',
      ],
      { 13157: 52793, 13158: 52796 },
      { 2: 7.299999999999997, 7: 0 },
      [],
    ],
    55946: [
      [
        129,
        -4,
        { src: '', width: 0, height: 0, _x: 0, _y: 0 },
        1,
        129,
        '2350970010-2005',
        0,
        0,
        179,
        1,
        {
          variant_thumbnail_path:
            'https:\/\/cdn.mmsports.se\/resized\/category\/D\/bsc-whey100-403g-belgianchocolate-medium-1pack.jpg',
        },
        7340224413815,
        'Smak: Belgian Chocolate Storlek: 400 g',
        0,
        '2026-05-03',
        false,
        '<h2>Body Science Whey 100% Belgian Chocolate<\/h2>\r\n<p><strong>Proteinpulver med smak av belgisk choklad. Inneh&aring;ller s&ouml;tningsmedel. Inneh&aring;ller laktasenzym.<br>Nettovikt:<\/strong>&nbsp;403 g (13 portioner).<br><strong>Portionsstorlek:<\/strong>&nbsp;31 g (~1 dl).&nbsp;Skopa ing&aring;r ej.<\/p>\r\n<p><strong>Anv&auml;ndning:<\/strong>&nbsp;<span class="TextRun SCXW32296401 BCX8" lang="SV-SE" xml:lang="SV-SE"><span class="NormalTextRun SCXW32296401 BCX8">Blanda 3<\/span><span class="NormalTextRun SCXW32296401 BCX8">1<\/span><span class="NormalTextRun SCXW32296401 BCX8">&nbsp;<\/span><span class="NormalTextRun SCXW32296401 BCX8">g<\/span><span class="NormalTextRun SCXW32296401 BCX8">&nbsp;<\/span><span class="NormalTextRun SCXW32296401 BCX8">med 2 dl vatten eller laktosfri mj&ouml;lk. M&auml;ngden v&auml;tska kan &ouml;kas eller minskas efter behov. Rekommenderat intag:&nbsp;<\/span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW32296401 BCX8">2<\/span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW32296401 BCX8">-<\/span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW32296401 BCX8">3<\/span><span class="NormalTextRun SCXW32296401 BCX8">&nbsp;portioner per dag.<\/span><\/span><span class="EOP SCXW32296401 BCX8">&nbsp;<\/span><\/p>\r\n<p><strong>Ingredienser:<\/strong> <span class="TextRun SCXW196150589 BCX8" lang="SV-SE" xml:lang="SV-SE" data-contrast="none"><span class="NormalTextRun SCXW196150589 BCX8">V<\/span><span class="NormalTextRun SCXW196150589 BCX8">assleproteinkoncentrat fr&aring;n&nbsp;<\/span><\/span><strong><span class="TextRun SCXW196150589 BCX8" lang="SV-SE" xml:lang="SV-SE" data-contrast="none"><span class="NormalTextRun SCXW196150589 BCX8">mj&ouml;lk<\/span><\/span><\/strong><span class="TextRun SCXW196150589 BCX8" lang="SV-SE" xml:lang="SV-SE" data-contrast="none"><span class="NormalTextRun SCXW196150589 BCX8"><strong>&nbsp;<\/strong>(inneh&aring;ller emulgeringsmedel&nbsp;<\/span><span class="NormalTextRun SCXW196150589 BCX8">solros<\/span><span class="NormalTextRun SCXW196150589 BCX8">lecitin<\/span><span class="NormalTextRun SCXW196150589 BCX8">,&nbsp;<\/span><\/span><strong><span class="TextRun SCXW196150589 BCX8" lang="SV-SE" xml:lang="SV-SE" data-contrast="none"><span class="NormalTextRun SCXW196150589 BCX8">soja<\/span><\/span><\/strong><span class="TextRun SCXW196150589 BCX8" lang="SV-SE" xml:lang="SV-SE" data-contrast="none"><span class="NormalTextRun SCXW196150589 BCX8">lecitin<\/span><span class="NormalTextRun SCXW196150589 BCX8">),&nbsp;<\/span><span class="NormalTextRun SCXW196150589 BCX8">kakao,<\/span><span class="NormalTextRun SCXW196150589 BCX8">&nbsp;arom,&nbsp;<\/span><span class="NormalTextRun SCXW196150589 BCX8">stabiliseringsmedel (cellulosagummi),&nbsp;<\/span><span class="NormalTextRun SCXW196150589 BCX8">berg<\/span><span class="NormalTextRun SCXW196150589 BCX8">salt,&nbsp;<\/span><span class="NormalTextRun SCXW196150589 BCX8">s&ouml;tningsmedel (<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW196150589 BCX8">aspartam<\/span><span class="NormalTextRun SCXW196150589 BCX8">,&nbsp;<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW196150589 BCX8">acesulfam<\/span><span class="NormalTextRun SCXW196150589 BCX8">-K), laktasenzym. Inneh&aring;ller en&nbsp;<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW196150589 BCX8">fenylalanink&auml;lla<\/span><span class="NormalTextRun SCXW196150589 BCX8">.<\/span><\/span><span class="EOP SCXW196150589 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:644,&quot;335559739&quot;:0,&quot;335559740&quot;:240}">&nbsp;<\/span><\/p>\r\n<p><strong>B&auml;st f&ouml;re utg&aring;ngen av:<\/strong>&nbsp;Se st&auml;mpel.<\/p>\r\n<p><strong>F&ouml;rvaringsanvisning:&nbsp;<\/strong><span class="NormalTextRun SCXW156182286 BCX8">I<\/span><span class="NormalTextRun SCXW156182286 BCX8">&nbsp;originalf&ouml;rpackning i rumstemperatur.<\/span><\/p>\r\n<table style="width: 100%; border: 1px solid #000000;" border="1" cellspacing="0" cellpadding="3">\r\n<tbody>\r\n<tr>\r\n<td colspan="3"><strong>N&auml;ringsinneh&aring;ll per 100 g och per portion 31 g.<\/strong><\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Energi<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1541 kJ\/367 kcal<\/td>\r\n<td style="text-align: right;" align="center" valign="top">483 kJ\/115 kcal<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Fett<br>-varav m&auml;ttat fett<\/td>\r\n<td style="text-align: right;" align="center" valign="top">6,2 g<br>5,8 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">2,0 g<br>1,8 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Kolhydrater<br>-varav sockerarter<sup>1<\/sup><\/td>\r\n<td style="text-align: right;" align="center" valign="top">4,4 g<br>3,4 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1,4 g<br>1,1 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Protein<\/td>\r\n<td style="text-align: right;" align="center" valign="top">70 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">22 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Salt<\/td>\r\n<td style="text-align: right;" align="center" valign="top">2,18 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">0,68 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td colspan="3">&nbsp;<\/td>\r\n<\/tr>\r\n<tr>\r\n<td colspan="3"><sup>1&nbsp;<\/sup>Inneh&aring;ller naturligt f&ouml;rekommande socker.<\/td>\r\n<\/tr>\r\n<\/tbody>\r\n<\/table>\r\n<p>&nbsp;<\/p>\r\n<p><strong>&Ouml;vrig information:&nbsp;<\/strong>MM Sports str&auml;var efter att alltid ge dig korrekt information. Eftersom mindre f&ouml;r&auml;ndringar i produktinneh&aring;llet kan ske &ouml;ver tid, uppmanar vi dig att kontrollera informationen p&aring; produktens f&ouml;rpackning innan anv&auml;ndning.<\/p>',
      ],
      { 13158: 54146, 13157: 52793 },
      { 2: 7.299999999999997, 7: 0 },
      [],
    ],
    55947: [
      [
        129,
        606,
        { src: '', width: 0, height: 0, _x: 0, _y: 0 },
        1,
        129,
        '2350970010-2006',
        0,
        0,
        179,
        1,
        {
          variant_thumbnail_path:
            'https:\/\/cdn.mmsports.se\/resized\/category\/D\/bsc-whey100-applepie-403g-medium-1pack-260203.jpg',
        },
        7340224414041,
        'Storlek: 400 g Smak: Apple Pie',
        0,
        null,
        false,
        '<h2>Body Science Whey 100% Apple Pie<\/h2>\r\n<p><strong>Proteinpulver med smak av &auml;ppelpaj. Inneh&aring;ller s&ouml;tningsmedel. Inneh&aring;ller laktasenzym.<br>Nettovikt:<\/strong>&nbsp;403 g (13 portioner).<br><strong>Portionsstorlek:<\/strong>&nbsp;31 g (~1 dl).&nbsp;Skopa ing&aring;r ej.<\/p>\r\n<p><strong>Anv&auml;ndning:<\/strong>&nbsp;<span class="TextRun SCXW32296401 BCX8" lang="SV-SE" xml:lang="SV-SE"><span class="NormalTextRun SCXW32296401 BCX8">Blanda 3<\/span><span class="NormalTextRun SCXW32296401 BCX8">1<\/span><span class="NormalTextRun SCXW32296401 BCX8">&nbsp;<\/span><span class="NormalTextRun SCXW32296401 BCX8">g<\/span><span class="NormalTextRun SCXW32296401 BCX8">&nbsp;<\/span><span class="NormalTextRun SCXW32296401 BCX8">med 2 dl vatten eller laktosfri mj&ouml;lk. M&auml;ngden v&auml;tska kan &ouml;kas eller minskas efter behov. Rekommenderat intag:&nbsp;<\/span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW32296401 BCX8">2<\/span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW32296401 BCX8">-<\/span><span class="NormalTextRun ContextualSpellingAndGrammarErrorV2Themed SCXW32296401 BCX8">3<\/span><span class="NormalTextRun SCXW32296401 BCX8">&nbsp;portioner per dag.<\/span><\/span><span class="EOP SCXW32296401 BCX8">&nbsp;<\/span><\/p>\r\n<p><strong>Ingredienser:<\/strong> <span class="TextRun SCXW264383416 BCX8" lang="SV-SE" xml:lang="SV-SE" data-contrast="none"><span class="NormalTextRun SCXW264383416 BCX8">V<\/span><span class="NormalTextRun SCXW264383416 BCX8">assleproteinkoncentrat fr&aring;n&nbsp;<\/span><\/span><strong><span class="TextRun SCXW264383416 BCX8" lang="SV-SE" xml:lang="SV-SE" data-contrast="none"><span class="NormalTextRun SCXW264383416 BCX8">mj&ouml;lk<\/span><\/span><\/strong><span class="TextRun SCXW264383416 BCX8" lang="SV-SE" xml:lang="SV-SE" data-contrast="none"><span class="NormalTextRun SCXW264383416 BCX8"><strong>&nbsp;<\/strong>(inneh&aring;ller emulgeringsmedel&nbsp;<\/span><span class="NormalTextRun SCXW264383416 BCX8">solros<\/span><span class="NormalTextRun SCXW264383416 BCX8">lecitin<\/span><span class="NormalTextRun SCXW264383416 BCX8">,&nbsp;<\/span><\/span><strong><span class="TextRun SCXW264383416 BCX8" lang="SV-SE" xml:lang="SV-SE" data-contrast="none"><span class="NormalTextRun SCXW264383416 BCX8">soja<\/span><\/span><\/strong><span class="TextRun SCXW264383416 BCX8" lang="SV-SE" xml:lang="SV-SE" data-contrast="none"><span class="NormalTextRun SCXW264383416 BCX8">lecitin<\/span><span class="NormalTextRun SCXW264383416 BCX8">),<\/span><span class="NormalTextRun SCXW264383416 BCX8">&nbsp;<\/span><\/span><strong><span class="TextRun SCXW264383416 BCX8" lang="SV-SE" xml:lang="SV-SE" data-contrast="none"><span class="NormalTextRun SCXW264383416 BCX8">havre<\/span><\/span><\/strong><span class="TextRun SCXW264383416 BCX8" lang="SV-SE" xml:lang="SV-SE" data-contrast="none"><span class="NormalTextRun SCXW264383416 BCX8">mj&ouml;l,<\/span><span class="NormalTextRun SCXW264383416 BCX8">&nbsp;<\/span><span class="NormalTextRun SCXW264383416 BCX8">arom,&nbsp;<\/span><span class="NormalTextRun SCXW264383416 BCX8">stabiliseringsmedel (cellulosagummi), kanel, salt,&nbsp;<\/span><span class="NormalTextRun SCXW264383416 BCX8">s&ouml;tningsmedel&nbsp;<\/span><span class="NormalTextRun SCXW264383416 BCX8">(<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW264383416 BCX8">aspartam<\/span><span class="NormalTextRun SCXW264383416 BCX8">,&nbsp;<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW264383416 BCX8">sukralos<\/span><span class="NormalTextRun SCXW264383416 BCX8">,&nbsp;<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW264383416 BCX8">acesulfam<\/span><span class="NormalTextRun SCXW264383416 BCX8">-K), laktasenzym. Inneh&aring;ller en&nbsp;<\/span><span class="NormalTextRun SpellingErrorV2Themed SCXW264383416 BCX8">fenylalanink&auml;lla<\/span><span class="NormalTextRun SCXW264383416 BCX8">.<\/span><\/span><span class="EOP SCXW264383416 BCX8" data-ccp-props="{&quot;201341983&quot;:0,&quot;335559685&quot;:644,&quot;335559739&quot;:0,&quot;335559740&quot;:240}">&nbsp;<\/span><\/p>\r\n<p><strong>B&auml;st f&ouml;re utg&aring;ngen av:<\/strong>&nbsp;Se st&auml;mpel.<\/p>\r\n<p><strong>F&ouml;rvaringsanvisning:&nbsp;<\/strong><span class="NormalTextRun SCXW156182286 BCX8">I<\/span><span class="NormalTextRun SCXW156182286 BCX8">&nbsp;originalf&ouml;rpackning i rumstemperatur.<\/span><\/p>\r\n<table style="width: 100%; border: 1px solid #000000;" border="1" cellspacing="0" cellpadding="3">\r\n<tbody>\r\n<tr>\r\n<td colspan="3"><strong>N&auml;ringsinneh&aring;ll per 100 g och per portion 31 g.<\/strong><\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Energi<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1554 kJ\/370 kcal<\/td>\r\n<td style="text-align: right;" align="center" valign="top">479 kJ\/114 kcal<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Fett<br>-varav m&auml;ttat fett<\/td>\r\n<td style="text-align: right;" align="center" valign="top">5,8 g<br>5,6 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1,8 g<br>1,7 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Kolhydrater<br>-varav sockerarter<sup>1<\/sup><\/td>\r\n<td style="text-align: right;" align="center" valign="top">7,1 g<br>3,7 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">2,2 g<br>1,1 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Protein<\/td>\r\n<td style="text-align: right;" align="center" valign="top">72 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">22 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td valign="top">Salt<\/td>\r\n<td style="text-align: right;" align="center" valign="top">1,27 g<\/td>\r\n<td style="text-align: right;" align="center" valign="top">0,39 g<\/td>\r\n<\/tr>\r\n<tr>\r\n<td colspan="3">&nbsp;<\/td>\r\n<\/tr>\r\n<tr>\r\n<td colspan="3"><sup>1&nbsp;<\/sup>Inneh&aring;ller naturligt f&ouml;rekommande socker.<\/td>\r\n<\/tr>\r\n<\/tbody>\r\n<\/table>\r\n<p>&nbsp;<\/p>\r\n<p><strong>&Ouml;vrig information:&nbsp;<\/strong>MM Sports str&auml;var efter att alltid ge dig korrekt information. Eftersom mindre f&ouml;r&auml;ndringar i produktinneh&aring;llet kan ske &ouml;ver tid, uppmanar vi dig att kontrollera informationen p&aring; produktens f&ouml;rpackning innan anv&auml;ndning.<\/p>',
      ],
      { 13157: 52793, 13158: 54147 },
      { 2: 7.299999999999997, 7: 0 },
      [],
    ],
  },
  modifiers: [],
  names: {
    13157: { class_name: 'Storlek', options: { 52793: '400 g' } },
    13158: {
      class_name: 'Smak',
      options: {
        54146: 'Belgian Chocolate',
        52795: 'Chocolate Cake',
        52794: 'Vanilla',
        52796: 'Strawberry',
        54147: 'Apple Pie',
      },
    },
  },
  multiple_select_enabled: false,
};
